// SPAKE2 over P-256, implemented to RFC 9382 (ciphersuite P256-SHA256-HKDF-
// HMAC) and proven against the RFC's published test vectors (Appendix B) in
// test/pairing.test.ts. SPAKE2 is the balanced PAKE that makes a short pairing
// code safe: an active man-in-the-middle who does not know the code gets one
// online guess per attempt and learns nothing offline from the transcript, so
// the host's K-try lockout caps the attacker at a 1-in-(charset^len) chance.
//
// Role assignment (RFC §3.1): A goes first and uses M; B goes second and uses
// N. We fix A = the connecting client, B = the host. Identities are hashed into
// the transcript so neither side can be tricked about who it paired with.

import {
  P256Point,
  P256_ORDER,
  sha256d,
  hmacSha256,
  hkdfSha256,
} from './crypto.js';
import { concatBytes, equalCt, utf8 } from './bytes.js';

// The SPAKE2 seed points for P-256, copied verbatim from RFC 9382 §6 (compressed
// SEC1). M is A's blinding point, N is B's. Their discrete logs are unknown by
// construction (generated by hashing a fixed seed to the curve), which is what
// the security proof requires.
const M_HEX = '02886e2f97ace46e55ba9dd7242579f2993b64e16ef3dcab95afd497333d8fa12f';
const N_HEX = '03d8bbd6c639c62937b04d997f38c3770719c629d7014d49a24b4f98baa1292b49';
const M = P256Point.fromHex(M_HEX);
const N = P256Point.fromHex(N_HEX);
const BASE = P256Point.BASE;

// P-256 has cofactor 1, so h*X == X; we keep the multiplication explicit in the
// comments to mirror the RFC, but there is no cofactor clearing to do.
const SCALAR_BYTES = 32; // length of p, for the big-endian encoding of w in TT
const HALF_HASH = 16; // |Ke| = |Ka| = |KcA| = |KcB| = 128 bits for SHA-256

export type SpakeRole = 'A' | 'B';

export interface SpakeIdentities {
  A: Uint8Array;
  B: Uint8Array;
  // Additional authenticated data, bound into the confirmation keys (RFC §4).
  // We pass the protocol header (version + mode) here so a pairing transcript
  // can never be replayed as a recovery transcript or across versions.
  aad?: Uint8Array;
}

export interface SpakeResult {
  // The shared secret to key the sealed channel with. 128 bits per the RFC;
  // callers expand it through HKDF before use.
  ke: Uint8Array;
  // The full transcript hash, Hash(TT). Both sides agree on it and it is secret
  // (it commits to K). Used as the salt binding the derived transport keys to
  // this exact handshake.
  transcriptHash: Uint8Array;
  // The MAC this party must send, and the MAC it must receive and verify.
  ourConfirm: Uint8Array;
  peerConfirmExpected: Uint8Array;
}

const le8 = (len: number): Uint8Array => {
  const b = new Uint8Array(8);
  new DataView(b.buffer).setBigUint64(0, BigInt(len), true);
  return b;
};
const lenPrefixed = (b: Uint8Array): Uint8Array => concatBytes(le8(b.length), b);

// Map a password (pairing code, recovery key, ...) to the SPAKE2 scalar w. RFC
// §3.2 leaves this to the application but recommends hashing to ~64 bits beyond
// the group size before reducing mod n, to erase modular bias. We derive 40
// bytes (320 bits ≥ 256+64) via HKDF with a domain-separating label.
export function deriveW(password: Uint8Array): bigint {
  const wide = hkdfSha256(password, new Uint8Array(0), utf8('FrontierLink/SPAKE2/v1 w'), 40);
  let w = 0n;
  for (const byte of wide) w = (w << 8n) | BigInt(byte);
  w %= P256_ORDER;
  // w == 0 would make pA/pB independent of the password; astronomically rare,
  // but we refuse rather than silently weaken.
  if (w === 0n) throw new Error('spake2: degenerate w (retry with a different code)');
  return w;
}

function decodeScalar(hexOrBytes: Uint8Array): bigint {
  let v = 0n;
  for (const byte of hexOrBytes) v = (v << 8n) | BigInt(byte);
  return v % P256_ORDER;
}

function wToBytes(w: bigint): Uint8Array {
  const out = new Uint8Array(SCALAR_BYTES);
  let v = w;
  for (let i = SCALAR_BYTES - 1; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

// One run of SPAKE2. Construct with the role, w, and identities; read `share`
// to send; call `finish(peerShare)` to derive the key + confirmation MACs.
export class Spake2 {
  private readonly w: bigint;
  private readonly xy: bigint; // our secret scalar (x for A, y for B)
  private readonly ids: SpakeIdentities;
  readonly role: SpakeRole;
  readonly share: Uint8Array; // pA (A) or pB (B), uncompressed SEC1 (65 bytes)

  // `fixedScalar` is test-only (the RFC vectors fix x and y). Production callers
  // omit it and a fresh random scalar is drawn.
  constructor(role: SpakeRole, w: bigint, ids: SpakeIdentities, fixedScalar?: bigint) {
    this.role = role;
    this.w = w % P256_ORDER;
    this.ids = ids;
    this.xy = fixedScalar !== undefined ? fixedScalar % P256_ORDER : randomScalar();
    if (this.xy === 0n) throw new Error('spake2: degenerate secret scalar');
    // pA = w*M + x*P ; pB = w*N + y*P
    const blind = role === 'A' ? M : N;
    const point = blind.multiply(this.w).add(BASE.multiply(this.xy));
    this.share = point.toBytes(false);
  }

  finish(peerShare: Uint8Array): SpakeResult {
    // RFC §7: validate group membership of the received element.
    let peer;
    try {
      peer = P256Point.fromBytes(peerShare);
      peer.assertValidity();
    } catch {
      throw new Error('spake2: peer share is not a valid curve point');
    }
    if (peer.is0()) throw new Error('spake2: peer share is the identity element');

    // A: K = h*x*(pB - w*N) ; B: K = h*y*(pA - w*M). Cofactor h = 1 on P-256.
    const unblind = this.role === 'A' ? N : M;
    const kPoint = peer.subtract(unblind.multiply(this.w)).multiply(this.xy);
    if (kPoint.is0()) throw new Error('spake2: degenerate shared point');
    const K = kPoint.toBytes(false);

    // The two shares appear in the transcript in protocol order: pA then pB.
    const pA = this.role === 'A' ? this.share : peerShare;
    const pB = this.role === 'A' ? peerShare : this.share;
    const TT = concatBytes(
      lenPrefixed(this.ids.A),
      lenPrefixed(this.ids.B),
      lenPrefixed(pA),
      lenPrefixed(pB),
      lenPrefixed(K),
      lenPrefixed(wToBytes(this.w)),
    );

    const hash = sha256d(TT);
    const ke = hash.slice(0, HALF_HASH);
    const ka = hash.slice(HALF_HASH);
    const confInfo = concatBytes(utf8('ConfirmationKeys'), this.ids.aad ?? new Uint8Array(0));
    const kc = hkdfSha256(ka, new Uint8Array(0), confInfo, 2 * HALF_HASH);
    const kcA = kc.slice(0, HALF_HASH);
    const kcB = kc.slice(HALF_HASH);
    const cA = hmacSha256(kcA, TT);
    const cB = hmacSha256(kcB, TT);

    return this.role === 'A'
      ? { ke, transcriptHash: hash, ourConfirm: cA, peerConfirmExpected: cB }
      : { ke, transcriptHash: hash, ourConfirm: cB, peerConfirmExpected: cA };
  }
}

// Verify a received confirmation MAC in constant time.
export function verifyConfirm(result: SpakeResult, received: Uint8Array): boolean {
  return equalCt(received, result.peerConfirmExpected);
}

function randomScalar(): bigint {
  // Draw 48 bytes (384 bits) and reduce, to keep the bias below 2^-128.
  const buf = new Uint8Array(48);
  globalThis.crypto.getRandomValues(buf);
  const v = decodeScalar(buf);
  return v === 0n ? 1n : v;
}

// Exposed only for the RFC-vector test, which supplies w, x, y as byte strings.
export const _test = { decodeScalar, wToBytes, M_HEX, N_HEX };
