// Package vectors generates spec/vectors/relay.json: key and id derivation, signed rosters
// (valid and invalid), registration signatures and routed frames, from fixed seeds.
package vectors

import (
	"bytes"
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"slices"

	"github.com/frontierengineer/link/relay/internal/link"
)

type keyVector struct {
	Seed          string `json:"seed"`
	Ed25519Seed   string `json:"ed25519Seed"`
	Ed25519       string `json:"ed25519"`
	X25519Private string `json:"x25519Private"`
	X25519        string `json:"x25519"`
	NodeID        string `json:"nodeId"`
	NodeIDRaw     string `json:"nodeIdRaw"`
}

type rosterVector struct {
	Description  string          `json:"description"`
	Roster       json.RawMessage `json:"roster"`
	JCS          string          `json:"jcs,omitempty"`
	SigningInput string          `json:"signingInput,omitempty"`
	Signature    string          `json:"signature,omitempty"`
	Valid        bool            `json:"valid"`
}

type registrationVector struct {
	Description string `json:"description"`
	Network     string `json:"network"`
	Node        string `json:"node"`
	Ed25519     string `json:"ed25519"`
	Challenge   string `json:"challenge"`
	Ts          uint64 `json:"ts"`
	Origin      string `json:"origin"`
	Message     string `json:"message"`
	Sig         string `json:"sig"`
}

type frameVector struct {
	Description string `json:"description"`
	Sent        string `json:"sent"`
	Delivered   string `json:"delivered"`
}

type file struct {
	About         []string             `json:"about"`
	Keys          []keyVector          `json:"keys"`
	Rosters       []rosterVector       `json:"rosters"`
	Registrations []registrationVector `json:"registrations"`
	Frames        []frameVector        `json:"frames"`
}

var b64 = link.B64u.EncodeToString

// Seeds are fixed; everything else follows from them (Ed25519 signatures are deterministic).
func seeds() [][]byte {
	inc := func(from byte) []byte {
		b := make([]byte, 32)
		for i := range b {
			b[i] = from + byte(i)
		}
		return b
	}
	return [][]byte{inc(0x00), inc(0x20), bytes.Repeat([]byte{0x42}, 32), bytes.Repeat([]byte{0xff}, 32)}
}

type rosterMember struct {
	k    *link.Keys
	kind string
}

func member(k *link.Keys, kind string) map[string]any {
	return map[string]any{"id": k.ID.String(), "ed25519": b64(k.Ed25519Public), "x25519": b64(k.X25519Public), "kind": kind}
}

// rosterObject builds an unsigned roster with members sorted by id.
func rosterObject(primary *link.Keys, version int64, ms ...rosterMember) map[string]any {
	list := make([]map[string]any, 0, len(ms))
	for _, m := range ms {
		list = append(list, member(m.k, m.kind))
	}
	slices.SortFunc(list, func(a, b map[string]any) int {
		return bytes.Compare([]byte(a["id"].(string)), []byte(b["id"].(string)))
	})
	members := make([]any, len(list))
	for i, m := range list {
		members[i] = m
	}
	return map[string]any{
		"network":  primary.ID.String(),
		"version":  version,
		"issuedAt": int64(1790000000000),
		"relay":    "wss://eu.frontierengineer.link/v1",
		"primary":  map[string]any{"ed25519": b64(primary.Ed25519Public)},
		"members":  members,
	}
}

func canonical(v map[string]any) json.RawMessage {
	b, err := link.Canonicalize(v)
	if err != nil {
		panic(err)
	}
	return b
}

func signedVector(desc string, r map[string]any, signer ed25519.PrivateKey) rosterVector {
	input, err := link.SigningInput(r)
	if err != nil {
		panic(err)
	}
	sig := ed25519.Sign(signer, input)
	r["signature"] = b64(sig)
	return rosterVector{
		Description:  desc,
		Roster:       canonical(r),
		JCS:          b64(input[len(link.RosterContext):]),
		SigningInput: b64(input),
		Signature:    b64(sig),
	}
}

// Generate returns the file's bytes.
func Generate() ([]byte, error) {
	var ks []*link.Keys
	f := file{About: []string{
		"Generated by relay/cmd/vectors; relay/internal/vectors checks this file matches. Do not edit.",
		"Binary values are b64u (base64url, no padding) unless named hex.",
		"keys: seed -> HKDF-derived Ed25519 seed and key, clamped X25519 private key and its public key, node id (b32 of the first 16 bytes of SHA-256(ed25519)) and its raw bytes in hex.",
		"rosters: roster is the full signed roster in JCS form. For signed cases jcs is JCS(roster without signature), signingInput is UTF-8(\"frontier-link/1/roster\") || jcs, signature is the Ed25519 signature. valid is whether a relay or member must find it valid (section 3).",
		"registrations: message is lenStr(\"frontier-link/1/register\") || lenStr(network) || lenStr(node) || challenge || u64be(ts) || lenStr(origin); sig is the node's Ed25519 signature over it.",
		"frames: a routed frame (hex) as a member sends it and as the relay delivers it, with the peer field rewritten to the sender's raw id (and control, type 8, delivered as data, type 3).",
	}}
	for _, s := range seeds() {
		k, err := link.DeriveKeys(s)
		if err != nil {
			return nil, err
		}
		ks = append(ks, k)
		f.Keys = append(f.Keys, keyVector{
			Seed: b64(s), Ed25519Seed: b64(k.Ed25519Seed), Ed25519: b64(k.Ed25519Public),
			X25519Private: b64(k.X25519Private), X25519: b64(k.X25519Public),
			NodeID: k.ID.String(), NodeIDRaw: hex.EncodeToString(k.ID[:]),
		})
	}
	a, b, c, d := ks[0], ks[1], ks[2], ks[3]
	all := []rosterMember{{a, link.KindPrimary}, {b, link.KindWorker}, {c, link.KindSurface}, {d, link.KindMCP}}

	valid := []rosterVector{
		signedVector("primary only, version 1", rosterObject(a, 1, all[0]), a.Ed25519),
		signedVector("every kind, version 12", rosterObject(a, 12, all...), a.Ed25519),
		signedVector("another network: seed 2 is the primary, seed 0 a worker", rosterObject(c, 3,
			rosterMember{c, link.KindPrimary}, rosterMember{a, link.KindWorker}), c.Ed25519),
	}
	for i := range valid {
		valid[i].Valid = true
	}
	f.Rosters = append(f.Rosters, valid...)

	invalid := func(desc string, mutate func(map[string]any), signer ed25519.PrivateKey) {
		r := rosterObject(a, 13, all...)
		mutate(r)
		f.Rosters = append(f.Rosters, signedVector(desc, r, signer))
	}
	members := func(r map[string]any) []any { return r["members"].([]any) }
	byID := func(r map[string]any, k *link.Keys) map[string]any {
		for _, m := range members(r) {
			if m.(map[string]any)["id"] == k.ID.String() {
				return m.(map[string]any)
			}
		}
		panic("no such member")
	}
	invalid("signed by a worker, not the primary", func(map[string]any) {}, b.Ed25519)
	invalid("members not sorted by id", func(r map[string]any) { m := members(r); m[0], m[1] = m[1], m[0] }, a.Ed25519)
	invalid("a member's id is not derived from its ed25519", func(r map[string]any) {
		byID(r, b)["ed25519"] = b64(c.Ed25519Public)
	}, a.Ed25519)
	invalid("network is not the node id of primary.ed25519", func(r map[string]any) {
		r["primary"] = map[string]any{"ed25519": b64(b.Ed25519Public)}
	}, b.Ed25519)
	invalid("two members of kind primary", func(r map[string]any) { byID(r, b)["kind"] = link.KindPrimary }, a.Ed25519)
	invalid("no member of kind primary", func(r map[string]any) { byID(r, a)["kind"] = link.KindWorker }, a.Ed25519)
	invalid("unknown kind", func(r map[string]any) { byID(r, d)["kind"] = "agent" }, a.Ed25519)
	invalid("version 0", func(r map[string]any) { r["version"] = int64(0) }, a.Ed25519)
	invalid("version is not an integer", func(r map[string]any) { r["version"] = 13.5 }, a.Ed25519)
	{
		// Changed after signing: the signature no longer covers it.
		v := signedVector("version changed after signing", rosterObject(a, 13, all...), a.Ed25519)
		var r map[string]any
		dec := json.NewDecoder(bytes.NewReader(v.Roster))
		dec.UseNumber()
		if err := dec.Decode(&r); err != nil {
			return nil, err
		}
		r["version"] = int64(14)
		f.Rosters = append(f.Rosters, rosterVector{Description: v.Description, Roster: canonical(r)})
	}

	challenge := make([]byte, 32)
	for i := range challenge {
		challenge[i] = byte(i + 1)
	}
	reg := func(desc string, k *link.Keys, network *link.Keys, ts uint64, origin string) {
		msg := link.RegisterMessage(network.ID.String(), k.ID.String(), challenge, ts, origin)
		f.Registrations = append(f.Registrations, registrationVector{
			Description: desc, Network: network.ID.String(), Node: k.ID.String(), Ed25519: b64(k.Ed25519Public),
			Challenge: b64(challenge), Ts: ts, Origin: origin, Message: b64(msg), Sig: b64(ed25519.Sign(k.Ed25519, msg)),
		})
	}
	reg("a worker on the public relay (default port omitted)", b, a, 1790000000000, "eu.frontierengineer.link")
	reg("the primary on a self-hosted relay with a port", a, a, 1790000123456, "relay.example:8443")

	body := []byte{0, 0, 0, 7, 0xde, 0xad, 0xbe, 0xef}
	sent := append(append([]byte{1, 0x03}, a.ID[:]...), body...)
	delivered := append(append([]byte{1, 0x03}, b.ID[:]...), body...)
	f.Frames = append(f.Frames, frameVector{
		Description: "data from seed 1 (worker) to seed 0 (primary), receiver index 7",
		Sent:        hex.EncodeToString(sent), Delivered: hex.EncodeToString(delivered),
	})
	unreach := append([]byte{1, 0x04}, c.ID[:]...)
	f.Frames = append(f.Frames, frameVector{
		Description: "a frame for seed 2, which is not connected, and the relay's unreachable answer (the peer field names seed 2)",
		Sent:        hex.EncodeToString(append(append([]byte{1, 0x01}, c.ID[:]...), 0, 0, 0, 1)), Delivered: hex.EncodeToString(unreach),
	})
	control := []byte{0, 0, 0, 7, 0x0c, 0x0a, 0xfe}
	f.Frames = append(f.Frames, frameVector{
		Description: "control from seed 1 to seed 0 (type 8), delivered as data (type 3): same body, peer rewritten",
		Sent:        hex.EncodeToString(append(append([]byte{1, 0x08}, a.ID[:]...), control...)),
		Delivered:   hex.EncodeToString(append(append([]byte{1, 0x03}, b.ID[:]...), control...)),
	})

	var out bytes.Buffer
	enc := json.NewEncoder(&out)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(f); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}
